import { NextRequest, NextResponse } from 'next/server';
import { authenticateRequest } from '@/lib/api-auth';
import { AutoGeneratedEventSyncService } from '@/services/business/autoGeneratedEventSyncService';

export async function GET(request: NextRequest) {
  try {
    const { user: currentUser, error } = await authenticateRequest();
    if (error) return error;
    if (!currentUser) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const deletedEventIds = await AutoGeneratedEventSyncService.getDeletedAnniversaryEventIds(currentUser.id);

    return NextResponse.json({ deletedEventIds });
  } catch (error) {
    console.error('Error fetching deleted anniversary events:', error);
    return NextResponse.json(
      { error: 'Failed to fetch deleted anniversary events' },
      { status: 500 }
    );
  }
}